### ISSUE TITLE
flask_nav: AttributeError: module 'collections' has no attribute 'MutableMapping'

### ISSUE THREAD

**Issue by louking** [louking/tm-csv-connector#1]
```
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 1063, in main
    cli.main()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1682, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1729, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 578, in get_command
    app = info.load_app()
  File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 312, in load_app
    app = locate_app(import_name, None, raise_if_not_found=False)
  File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 218, in locate_app
    __import__(module_name)
  File "/app/app.py", line 25, in <module>
    app = create_app(Production(configfiles), configfiles, init_for_operation=False)
  File "/app/tm_csv_connector/__init__.py", line 125, in create_app
    from . import nav
  File "/app/tm_csv_connector/nav.py", line 11, in <module>
    from flask_nav import Nav
  File "/usr/local/lib/python3.10/site-packages/flask_nav/__init__.py", line 49, in <module>
    class ElementRegistry(collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
```

**Comment by louking** [comment]
see https://stackoverflow.com/questions/70943244/attributeerror-module-collections-has-no-attribute-mutablemapping

**Comment by louking** [comment]
pip install flask-nav3 (supports python 3.10+)
