### ISSUE TITLE
TypeError: object NoneType can't be used in 'await' expression

### ISSUE THREAD

**Issue by louking** [louking/tm-csv-connector#11]
```
Exception in thread Thread-1 (reader_thread):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\lking\Documents\Lou's Software\projects\tm-csv-connector\tm-csv-connector\tm-reader-client\app.py", line 162, in reader_thread
    run(reader(port, logging_path))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\lking\Documents\Lou's Software\projects\tm-csv-connector\tm-csv-connector\tm-reader-client\app.py", line 152, in reader
    await send_to_backend(websocket, msg)
  File "C:\Users\lking\Documents\Lou's Software\projects\tm-csv-connector\tm-csv-connector\tm-reader-client\app.py", line 128, in send_to_backend
    await websocket.send(sending)
TypeError: object NoneType can't be used in 'await' expression
```

**Comment by louking** [comment]
needed to use websockets.connect()
