### ISSUE TITLE
tm-csv-reader logging: AttributeError: 'WebSocketClientProtocol' object has no attribute 'request_headers'

### ISSUE THREAD

**Issue by louking** [louking/tm-csv-connector#25]
```
2023-09-05 12:44:27,411 websockets.client INFO: ! connect failed again; retrying in 5 seconds
Traceback (most recent call last):
  File "C:\Users\lking\Documents\Lou's Software\projects\tm-csv-connector\tm-csv-connector\.venv\lib\site-packages\websockets\legacy\client.py", line 602, in __aiter__      
    async with self as protocol:
  File "C:\Users\lking\Documents\Lou's Software\projects\tm-csv-connector\tm-csv-connector\.venv\lib\site-packages\websockets\legacy\client.py", line 637, in __aenter__     
    return await self
  File "C:\Users\lking\Documents\Lou's Software\projects\tm-csv-connector\tm-csv-connector\.venv\lib\site-packages\websockets\legacy\client.py", line 655, in __await_impl_timeout__
    return await self.__await_impl__()
  File "C:\Users\lking\Documents\Lou's Software\projects\tm-csv-connector\tm-csv-connector\.venv\lib\site-packages\websockets\legacy\client.py", line 659, in __await_impl__ 
    _transport, _protocol = await self._create_connection()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 1103, in create_connection        
    transport, protocol = await self._create_connection_transport(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 1121, in _create_connection_transport
    protocol = protocol_factory()
  File "C:\Users\lking\Documents\Lou's Software\projects\tm-csv-connector\tm-csv-connector\.venv\lib\site-packages\websockets\legacy\client.py", line 99, in __init__        
    super().__init__(logger=logger, **kwargs)
  File "C:\Users\lking\Documents\Lou's Software\projects\tm-csv-connector\tm-csv-connector\.venv\lib\site-packages\websockets\legacy\protocol.py", line 255, in __init__     
    self.logger.debug("= connection is CONNECTING")
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1835, in debug
    self.log(DEBUG, msg, *args, **kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1879, in log
    self.logger.log(level, msg, *args, **kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1878, in log
    msg, kwargs = self.process(msg, kwargs)
  File "C:\Users\lking\Documents\Lou's Software\projects\tm-csv-connector\tm-csv-connector\tm-reader-client\app.py", line 56, in process
    xff = websocket.request_headers.get("X-Forwarded-For")
AttributeError: 'WebSocketClientProtocol' object has no attribute 'request_headers'
```

**Comment by louking** [comment]
resolved with dafc9c682d6bfe1324a41a6d4f7b72daa17275d0
