### ISSUE TITLE
tm-reader-client: couple of instances of SerialException: could not open port 'COM4': OSError(22, 'The semaphore timeout period has expired.', None, 121)

### ISSUE THREAD

**Issue by louking** [louking/tm-csv-connector#26]
```
2023-09-06 06:46:35,822 tm-csv-connector INFO: time machine async reader started with port COM4
Exception in thread Thread-2 (reader_thread):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\lking\Documents\Lou's Software\projects\tm-csv-connector\tm-csv-connector\tm-reader-client\app.py", line 205, in reader_thread
    run(reader(port, logging_path))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 649, in run_until_complete 
    return future.result()
  File "C:\Users\lking\Documents\Lou's Software\projects\tm-csv-connector\tm-csv-connector\tm-reader-client\app.py", line 164, in reader
    transport, protocol = await create_serial_connection(readloop, InputChunkProtocol, port)
  File "C:\Users\lking\Documents\Lou's Software\projects\tm-csv-connector\tm-csv-connector\.venv\lib\site-packages\serial_asyncio\__init__.py", line 448, in create_serial_connection
    serial_instance = serial.serial_for_url(*args, **kwargs)
  File "C:\Users\lking\Documents\Lou's Software\projects\tm-csv-connector\tm-csv-connector\.venv\lib\site-packages\serial\__init__.py", line 90, in serial_for_url    
    instance.open()
  File "C:\Users\lking\Documents\Lou's Software\projects\tm-csv-connector\tm-csv-connector\.venv\lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM4': OSError(22, 'The semaphore timeout period has expired.', None, 121)
```

**Comment by louking** [comment]
This seems to occur if connect is issued before time machine is ready. Will reopen if seen to occur at other times.

**Comment by louking** [comment]
This occurs sometimes even with time machine is ready.

**Comment by louking** [comment]
see https://stackoverflow.com/questions/13999439/the-semaphore-timeout-period-has-expired-error-for-usb-connection
