### ISSUE TITLE
run tm-reader-client as windows service

### ISSUE THREAD

**Issue by louking** [louking/tm-csv-connector#31]
create separate exe to read from time machine and pipe somehow to the app container

- https://pyinstaller.org/en/stable/
- start windows app as service:  
  - https://stackoverflow.com/a/32440
  - https://stackoverflow.com/a/46450007

`pyinstaller tm-reader-client/app.py --version-file app/src/tm_csv_connector/version.py -n tm-csv-connector`

**Comment by louking** [comment]
```
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\lking\Documents\Lou's Software\projects\tm-csv-connector\tm-csv-connector\.venv\scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "c:\Users\lking\Documents\Lou's Software\projects\tm-csv-connector\tm-csv-connector\.venv\lib\site-packages\PyInstaller\__main__.py", line 194, in _console_script_run
    run()
  File "c:\Users\lking\Documents\Lou's Software\projects\tm-csv-connector\tm-csv-connector\.venv\lib\site-packages\PyInstaller\__main__.py", line 180, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\Users\lking\Documents\Lou's Software\projects\tm-csv-connector\tm-csv-connector\.venv\lib\site-packages\PyInstaller\__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\Users\lking\Documents\Lou's Software\projects\tm-csv-connector\tm-csv-connector\.venv\lib\site-packages\PyInstaller\building\build_main.py", line 1019, in main      
    build(specfile, distpath, workpath, clean_build)
  File "c:\Users\lking\Documents\Lou's Software\projects\tm-csv-connector\tm-csv-connector\.venv\lib\site-packages\PyInstaller\building\build_main.py", line 944, in build      
    exec(code, spec_namespace)
  File "C:\Users\lking\Documents\Lou's Software\projects\tm-csv-connector\tm-csv-connector\tm-csv-connector.spec", line 24, in <module>
    exe = EXE(
  File "c:\Users\lking\Documents\Lou's Software\projects\tm-csv-connector\tm-csv-connector\.venv\lib\site-packages\PyInstaller\building\api.py", line 565, in __init__
    self.versrsrc = versioninfo.load_version_info_from_text_file(self.versrsrc)
  File "c:\Users\lking\Documents\Lou's Software\projects\tm-csv-connector\tm-csv-connector\.venv\lib\site-packages\PyInstaller\utils\win32\versioninfo.py", line 575, in load_version_info_from_text_file
    raise ValueError("Failed to deserialize VSVersionInfo from text-based representation!") from e
ValueError: Failed to deserialize VSVersionInfo from text-based representation!

```

**Comment by louking** [comment]
from dist directory:

```
nssm-2.24/win64/nssm install TmCsvConnector "C:\Users\lking\Documents\Lou's Software\projects\tm-csv-connector\tm-csv-connector\dist\tm-csv-connector\tm-csv-connector"
nssm-2.24/win64/nssm set TmCsvConnector Description "Time Machine CSV Connector"
nssm-2.24/win64/nssm start TmCsvConnector
```
